create database class;
create table class(regd int(10) primary key not null,
name_student varchar(23) not null,
brach varchar(10) not null,
class varchar(10) not null,
section int(5) not null
);
INSERT INTO class VALUES (1,"BHARATH","ECE","B.TECH",1);
INSERT INTO class VALUES (2,"BHEEMA","MECH","B.TECH",2);
INSERT INTO class VALUES (3,"RAJU","ECE","B.TECH",4);
INSERT INTO class VALUES (4,"HARI","CSE","B.TECH",2);
INSERT INTO class VALUES (5,"PAWAN","ECE","B.TECH",5);
INSERT INTO class VALUES (6,"NANI","EEE","B.TECH",2);
INSERT INTO class VALUES (7,"PANDU","CSE","B.TECH",2);
INSERT INTO class VALUES (8,"AJAY","ECE","B.TECH",3);
INSERT INTO class VALUES (9,"RAMU","MECH","B.TECH",2);
INSERT INTO class VALUES (10,"SREEKANTH","CSE","B.TECH",1);
INSERT INTO class VALUES (11,"JASWANTH","ECE","B.TECH",1);
INSERT INTO class VALUES (12,"JAGAN","CSE","B.TECH",2);
INSERT INTO class VALUES (13,"CHARAN","CIVIL","B.TECH",3);
-- TO SEE ALL THE TABLE
SELECT * FROM class;
-- TO SEE ALL THE DATA WITH COLOMN HAVING CLASS B.TECH
SELECT * FROM class WHERE class = "b.tech";
-- TO SEE ALL THE DATA WITH COLOMN HAVING SECTION =2
SELECT * FROM class WHERE section = 2;
-- TO SEE ALL THE DATA WITH COLOMN HAVING brach="CSE" AND SECTION =2
SELECT * FROM class WHERE section = 2 AND brach="CSE";
-- TO SEE ALL THE DATA WITH STUDENT NAME BEGIN WITH B
SELECT * FROM class WHERE name_student LIKE "B%";
-- TO SEE ALL THE DATA WITH STUDENT NAME BEGIN WITH BH
SELECT * FROM class WHERE name_student LIKE "BH%";
-- TO SEE ALL THE DATA WITH STUDENT NAME END WITH A
SELECT * FROM class WHERE name_student LIKE "%A";
-- TO SEE IN THE MIDDLE WITH SPECIFIC ALPHABET/WORD
SELECT * FROM class WHERE name_student LIKE "_A%";


-- TO SEE ALL THE DATA WITH STUDENT NAME  NOT BEGIN WITH A
SELECT * FROM class WHERE name_student NOT LIKE "%A";
